Catastrophe.create(name: 'Incendio en Nueva York',
                   description: 'Un incendio fue reportado en Nueva York, cerca de Midtown Manhattan, parece haber sido una falla de una planta de energia electrica.',
                   affected_people: 58,
                   affected_surface: 436,
                   drones: 3,
                   agents_online: 23,
                   lat: 40.71347,
                   lng: -74.00408,
                   affected_buildings: 7,
                   people_rescued: 32,
                   building_rescued: 2,
                   location: 'Midtown Manhattan, New York, NY')

Catastrophe.create(name: 'Inundación en Seattle',
                   description: 'Dos manzanas cerca de Delridge se han inundado.',
                   affected_people: 22,
                   affected_surface: 562,
                   drones: 4,
                   agents_online: 2,
                   lat: 47.614848,
                   lng: -122.3359059,
                   affected_buildings: 0,
                   people_rescued: 12,
                   building_rescued: 0,
                   location: 'Delridge, Seattle, WA')
Catastrophe.create(name: 'Inundanción de Comodoro Rivadavia',
                   description: 'Se ha reportado una gran inundación en la ciudad, comenzando por la zona de Av. Ducos.',
                   affected_people: 22,
                   affected_surface: 25213,
                   drones: 4,
                   agents_online: 3,
                   lat: -45.8648959,
                   lng: -67.4913697,
                   affected_buildings: 0,
                   people_rescued: 12,
                   building_rescued: 0,
                   location: 'Comodoro Rivadavia, Chubut, Argentina')
